# whitelist
branches:
  only:
#    - master
#    - develop
    - full-rewrite

language: python
dist: xenial   # required for Python >= 3.7
python:
  - "3.5"
  - "3.6"
  - "3.7"


install:
  - pip install -r requirements.txt
  - pip install -v .

# command to run tests
script:
  - pytest -v fatslim/test


